import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.css'
import { store } from '@/src/store/index';
import { Providers } from '@/src/store/providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>

  )
}